[@@@comment "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]
class date (x3 : Ojs.t) =
  let date_to_js (x1 : date) = (x1#to_js : Ojs.t)
  
  and date_of_js (x2 : Ojs.t) = ((new date) x2 : date)
   in let _ = date_to_js
      
      and _ = date_of_js
       in
  object
    inherit  (Ojs.obj x3)
    method get_date : int = Ojs.int_of_js (Ojs.get x3 "getDate")
    method get_day : int = Ojs.int_of_js (Ojs.get x3 "getDay")
    method get_full_year : int = Ojs.int_of_js (Ojs.get x3 "getFullYear")
    method get_hours : int = Ojs.int_of_js (Ojs.get x3 "getHours")
    method get_milliseconds : int =
      Ojs.int_of_js (Ojs.get x3 "getMilliseconds")
    method get_minutes : int = Ojs.int_of_js (Ojs.get x3 "getMinutes")
    method get_month : int = Ojs.int_of_js (Ojs.get x3 "getMonth")
    method get_secondes : int = Ojs.int_of_js (Ojs.get x3 "getSecondes")
    method get_time : int = Ojs.int_of_js (Ojs.get x3 "getTime")
    method get_timezone_offset : int =
      Ojs.int_of_js (Ojs.get x3 "getTimezoneOffset")
    method get_UTC_date : int = Ojs.int_of_js (Ojs.get x3 "getUTCDate")
    method get_UTC_day : int = Ojs.int_of_js (Ojs.get x3 "getUTCDay")
    method get_UTC_full_year : int =
      Ojs.int_of_js (Ojs.get x3 "getUTCFullYear")
    method get_UTC_hours : int = Ojs.int_of_js (Ojs.get x3 "getUTCHours")
    method get_UTC_milliseconds : int =
      Ojs.int_of_js (Ojs.get x3 "getUTCMilliseconds")
    method get_UTC_minutes : int = Ojs.int_of_js (Ojs.get x3 "getUTCMinutes")
    method get_UTC_month : int = Ojs.int_of_js (Ojs.get x3 "getUTCMonth")
    method get_UTC_seconds : int = Ojs.int_of_js (Ojs.get x3 "getUTCSeconds")
    method now : int = Ojs.int_of_js (Ojs.get x3 "now")
    method parse : string -> int =
      fun x4  ->
        Ojs.int_of_js (Ojs.call x3 "parse" [|(Ojs.string_to_js x4)|])
    method set_date : int -> unit =
      fun x5  -> Ojs.set x3 "setDate" (Ojs.int_to_js x5)
    method set_day : int -> unit =
      fun x6  -> Ojs.set x3 "setDay" (Ojs.int_to_js x6)
    method set_full_year : int -> unit =
      fun x7  -> Ojs.set x3 "setFullYear" (Ojs.int_to_js x7)
    method set_hours : int -> unit =
      fun x8  -> Ojs.set x3 "setHours" (Ojs.int_to_js x8)
    method set_milliseconds : int -> unit =
      fun x9  -> Ojs.set x3 "setMilliseconds" (Ojs.int_to_js x9)
    method set_minutes : int -> unit =
      fun x10  -> Ojs.set x3 "setMinutes" (Ojs.int_to_js x10)
    method set_month : int -> unit =
      fun x11  -> Ojs.set x3 "setMonth" (Ojs.int_to_js x11)
    method set_secondes : int -> unit =
      fun x12  -> Ojs.set x3 "setSecondes" (Ojs.int_to_js x12)
    method set_time : int -> unit =
      fun x13  -> Ojs.set x3 "setTime" (Ojs.int_to_js x13)
    method set_timezone_offset : int -> unit =
      fun x14  -> Ojs.set x3 "setTimezoneOffset" (Ojs.int_to_js x14)
    method set_UTC_date : int -> unit =
      fun x15  -> Ojs.set x3 "setUTCDate" (Ojs.int_to_js x15)
    method set_UTC_day : int -> unit =
      fun x16  -> Ojs.set x3 "setUTCDay" (Ojs.int_to_js x16)
    method set_UTC_full_year : int -> unit =
      fun x17  -> Ojs.set x3 "setUTCFullYear" (Ojs.int_to_js x17)
    method set_UTC_hours : int -> unit =
      fun x18  -> Ojs.set x3 "setUTCHours" (Ojs.int_to_js x18)
    method set_UTC_milliseconds : int -> unit =
      fun x19  -> Ojs.set x3 "setUTCMilliseconds" (Ojs.int_to_js x19)
    method set_UTC_minutes : int -> unit =
      fun x20  -> Ojs.set x3 "setUTCMinutes" (Ojs.int_to_js x20)
    method set_UTC_month : int -> unit =
      fun x21  -> Ojs.set x3 "setUTCMonth" (Ojs.int_to_js x21)
    method set_UTC_seconds : int -> unit =
      fun x22  -> Ojs.set x3 "setUTCSeconds" (Ojs.int_to_js x22)
    method to_date_string : string =
      Ojs.string_of_js (Ojs.get x3 "toDateString")
    method to_ISO_string : string =
      Ojs.string_of_js (Ojs.get x3 "toISOString")
    method to_JSON : string = Ojs.string_of_js (Ojs.get x3 "toJSON")
    method to_locale_date_string : string =
      Ojs.string_of_js (Ojs.get x3 "toLocaleDateString")
    method to_locale_time_string : string =
      Ojs.string_of_js (Ojs.get x3 "toLocaleTimeString")
    method to_locale_string : string =
      Ojs.string_of_js (Ojs.get x3 "toLocaleString")
    method to_string : string = Ojs.string_of_js (Ojs.get x3 "toString")
    method to_time_string : string =
      Ojs.string_of_js (Ojs.get x3 "toTimeString")
    method to_UTC_string : string =
      Ojs.string_of_js (Ojs.get x3 "toUTCString")
    method utc : int = Ojs.int_of_js (Ojs.call x3 "UTC" [||])
    method value_of : int = Ojs.int_of_js (Ojs.get x3 "valueOf")
  end
let date_to_js (x1 : date) = (x1#to_js : Ojs.t)

and date_of_js (x2 : Ojs.t) = ((new date) x2 : date)

let (date :unit -> date)=
  fun ()  -> date_of_js (Ojs.new_obj (Ojs.get Ojs.global "Date") [||]) 
let (date_milli :int -> date)=
  fun x23  ->
    date_of_js
      (Ojs.new_obj (Ojs.get Ojs.global "Date") [|(Ojs.int_to_js x23)|])
  
let (date_str :string -> date)=
  fun x24  ->
    date_of_js
      (Ojs.new_obj (Ojs.get Ojs.global "Date") [|(Ojs.string_to_js x24)|])
  
let (date_full :int -> int -> int -> int -> int -> int -> int -> date)=
  fun x25  ->
    fun x26  ->
      fun x27  ->
        fun x28  ->
          fun x29  ->
            fun x30  ->
              fun x31  ->
                date_of_js
                  (Ojs.new_obj (Ojs.get Ojs.global "Date")
                     [|(Ojs.int_to_js x25);(Ojs.int_to_js x26);(Ojs.int_to_js
                                                                  x27);(
                       Ojs.int_to_js x28);(Ojs.int_to_js x29);(Ojs.int_to_js
                                                                 x30);(
                       Ojs.int_to_js x31)|])
  
